### ISSUE TITLE
Change unused function parameters from error to warning

### ISSUE THREAD

**Issue by dunkelstern** [anfema/eslint-config-anfema#4]
Sometimes it makes sense to keep parameters in functions (for example refactoring, but keeping an external interface stable)

**Comment by pichfl** [comment]
As of now ESLint [no-unused-vars](http://eslint.org/docs/rules/no-unused-vars) is responsible for this check. We should consider file an upstream request to split this rule into two separate rules. 

I prefer to error if an unused variable is kept inside code. I could disable the check for params completely, but I'd rather not do that. 

For now, use JSDocs to define the interface and a block comment as needed.

```js
/**
 * @param a {string}
 * @param b {string} unused, reserved for later usage
 * @returns {string}
 */
function c(a/* , b */) {
    return a;
}
```

I'll keep an eye on this, hopefully we can update in the future.
